---
- name: "roles/langs.python/tasks/main: Install python v3.9.6 from xbuild"
  become_user: isucon
  command: /tmp/xbuild/python-install 3.9.6 /home/isucon/local/python

- name: "roles/langs.python/tasks/main: Add PATH for python"
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK python"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/python/bin:$PATH
