---
- name: "roles/common/tasks/user: Create isucon group"
  become_user: root
  group:
    name: isucon
    gid: 1100
    state: present
    system: no

- name: "roles/common/tasks/user: Create isucon user"
  become_user: root
  user:
    name: isucon
    uid: 1100
    group: isucon
    password: $1$SALTsalt$e7jg2tj3sKVpmYXXmivBb0
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: "roles/common/tasks/user: Create isucon-admin group"
  become_user: root
  group:
    name: isucon-admin
    gid: 1200
    state: present
    system: no

- name: "roles/common/tasks/user: Create isucon-admin user"
  become_user: root
  user:
    name: isucon-admin
    uid: 1200
    group: isucon-admin
    password: $1$SALTsalt$e7jg2tj3sKVpmYXXmivBb0
    home: /home/isucon-admin
    shell: /bin/bash
    state: present
    system: no

- name: "roles/common/tasks/user: Add sudoers"
  become_user: root
  copy:
    content: |
      isucon        ALL=(ALL) NOPASSWD:ALL
      isucon-admin  ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/99-isucon-user
    owner: root
    group: root
    mode: 0440

- name: "roles/common/tasks/user: Create .ssh directory for isucon user"
  become_user: isucon
  file:
    path: /home/isucon/.ssh
    state: directory
    mode: 0700

- name: "roles/common/tasks/user: Create .ssh directory for isucon-admin user"
  become_user: isucon-admin
  file:
    path: /home/isucon-admin/.ssh
    state: directory
    mode: 0700

- name: "roles/common/tasks/user: Deploy pubkey to isucon-admin user"
  become_user: isucon-admin
  copy:
    src: id_ecdsa.pub
    dest: /home/isucon-admin/.ssh/authorized_keys
    mode: 0600
