---
- name: "roles/contestant/tasks/isucondition-go: Build Web Application Go"
  become_user: isucon
  args:
    chdir: /home/isucon/webapp/go/
  environment:
    PATH: "/home/isucon/local/go/bin:{{ ansible_env.PATH }}"
  shell: |
    go build -o isucondition .

