---
- name: "roles/contestant/tasks/isucondition-perl: Build Web Application Perl"
  become_user: isucon
  environment:
    PATH: "/home/isucon/local/perl/bin:{{ ansible_env.PATH }}"
  args:
    chdir: /home/isucon/webapp/perl
  shell: |
    /home/isucon/local/perl/bin/cpm install -g --show-build-log-on-failure

