apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: nginx
    app.kubernetes.io/name: myapp
    app.kubernetes.io/version: v1.0.0
    name: myapp
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
