apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-grafana-datasource
  labels:
      grafana_datasource: "true"
data:
  datasource.yaml: |-
     apiVersion: 1
     datasources:
     - name: Prometheus-server
       type: prometheus
       access: proxy
       orgId: 1
       url: http://prometheus-example-service:9090
       isDefault: true
