---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pushgateway-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.9.0
    heritage: Helm
    release: pushgateway
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-prometheus-pushgateway
  annotations:
    {}
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.9.0
    heritage: Helm
    release: pushgateway
spec:
  clusterIP: 
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
    release: pushgateway
---
# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.9.0
    heritage: Helm
    release: pushgateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-pushgateway
      release: pushgateway
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
        release: pushgateway
      annotations:
        {}
    spec:
      serviceAccountName: pushgateway-prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v1.3.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
---
# Source: prometheus-pushgateway/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway-prometheus-pushgateway
  namespace: cattle-prometheus
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.9.0
    heritage: Helm
    release: pushgateway
spec:
  endpoints:
  - port: http
    path: /metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
      - cattle-prometheus
  selector:
    matchLabels:
      app: prometheus-pushgateway
      release: pushgateway

