---
- name: "roles/bench.supervisor/tasks/generate_env: Deploy generate-env.sh"
  tags:
    - aws
  become_user: root
  copy:
    src: "home/isucon/bin/generate-env_aws.sh"
    dest: "/home/isucon/bin/generate-env.sh"
    owner: "isucon"
    group: "isucon"
    mode: "0755"
