---
- name: "roles/bench/tasks/bench: Deploy isucon11-qualify bench & source data (webapp/frontend)"
  become_user: isucon
  copy:
    remote_src: yes
    src: "{{ item }}"
    dest: /home/isucon/
    owner: isucon
    group: isucon
  with_items:
    - /tmp/isucon11-qualify/bench
    - /tmp/isucon11-qualify/webapp

- name: "roles/bench/tasks/bench: Deploy initial-data for bench"
  become_user: isucon
  copy:
    src: "initialize.json"
    dest: /home/isucon/bench/data/
    owner: isucon
    group: isucon

- name: "roles/bench/tasks/bench: Build Web Application Go"
  become_user: isucon
  args:
    chdir: /home/isucon/bench
  environment:
    PATH: "/home/isucon/local/go/bin:{{ ansible_env.PATH }}"
  shell: |
    make build RELEASE=1
