---
- name: "roles/bench/tasks/nofile: Deploy nofile.conf for FD limitation"
  copy:
    dest: /etc/security/limits.d/nofile.conf
    content: |
      root soft nofile 1048576
      root hard nofile 1048576
      * soft nofile 1048576
      * hard nofile 1048576
