apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: kafka-exporter
version: 1.1.0
home: https://github.com/abhishekjiitr/kafka-exporter-helm
maintainers:
  - name: nwiizo
    email: syu.m.5151@gmail.com
